"""vidapi - Standalone video download API for BiliBili and YouTube."""

from .core import (
    extract_urls,
    classify_site,
    normalize_url,
    extract_concatenated_urls,
    build_format_selector,
    quality_to_height,
    describe_selected_formats,
    selected_video_height,
    get_bilibili_cookie_candidates,
    cookie_candidate_to_spec,
    inspect_bilibili_cookie_jar,
    verify_bilibili_cookie_jar,
    build_cookie_header,
    is_bilibili_cookie,
    get_downloads_folder,
    detect_system_proxy,
    get_ffmpeg_location,
    format_bytes,
    format_eta,
    Config,
    get_config,
    DownloadSession,
    CookieSession,
    QueueLogger,
    AsyncThreadRunner,
    SessionThreadRunner,
)
from .main import app

__version__ = "0.1.0"
__all__ = [
    "app",
    "extract_urls",
    "classify_site",
    "normalize_url",
    "extract_concatenated_urls",
    "build_format_selector",
    "quality_to_height",
    "describe_selected_formats",
    "selected_video_height",
    "get_bilibili_cookie_candidates",
    "cookie_candidate_to_spec",
    "inspect_bilibili_cookie_jar",
    "verify_bilibili_cookie_jar",
    "build_cookie_header",
    "is_bilibili_cookie",
    "get_downloads_folder",
    "detect_system_proxy",
    "get_ffmpeg_location",
    "format_bytes",
    "format_eta",
    "Config",
    "get_config",
    "DownloadSession",
    "CookieSession",
    "QueueLogger",
    "AsyncThreadRunner",
    "SessionThreadRunner",
]